apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: quickstart
  pipedID: c76d43be-8776-4f76-82c4-d8899ebb71b7 ## Project name: pipecd-playground
  pipedKeyData: OXB6NXhpeTAwOHJwdjJ6anVmY3ZvOWI4OWt5dXV4NHVsMDVocjluNjcyNnZ3ZXZiZXQK ## Piped Key: 9pz5xiy008rpv2zjufcvo9b89kyuux4ul05hr9n6726vwevbet
  apiAddress: localhost:8080
  repositories:
    - repoId: pipecd-k8s-manifest-playground
      remote: https://github.com/GotoRen/pipecd-k8s-manifest-playground
      branch: main
  syncInterval: 1m
  platformProviders:
    - name: kubernetes-default
      type: KUBERNETES
      config:
        kubeConfigPath: /Users/ren/.kube/config
  notifications:
    routes:
      ### Webhook
      - name: pipecd-playground-webhook
        events:
          ## https://pipecd.dev/docs-v0.45.x/user-guide/managing-piped/configuring-notifications/
          ## https://github.com/pipe-cd/pipecd/blob/master/pkg/model/notificationevent.pb.go#L41-L55
          - DEPLOYMENT_TRIGGERED ##: 0
          - DEPLOYMENT_PLANNED ##: 1
          - DEPLOYMENT_APPROVED ##: 2
          - DEPLOYMENT_ROLLING_BACK ## 3: ロールバック
          - DEPLOYMENT_SUCCEEDED ## 4: デプロイ成功
          - DEPLOYMENT_FAILED ## 5: デプロイ失敗
          - DEPLOYMENT_CANCELLED ## 6: デプロイキャンセル
          - DEPLOYMENT_WAIT_APPROVAL ## 7
          - DEPLOYMENT_TRIGGER_FAILED ## 8
          - APPLICATION_SYNCED ## 100
          - APPLICATION_OUT_OF_SYNC ## 101
          - APPLICATION_HEALTHY ## 200
          - APPLICATION_UNHEALTHY ## none
          - PIPED_STARTED ## 300: PipeCD 起動
          - PIPED_STOPPED ## 301: PipeCD 停止
        labels:
          env: pipecd-playground
        receiver: pipecd-playground-webhook-receiver
    receivers:
      - name: pipecd-playground-webhook-receiver
        webhook:
          url: http://localhost:8081/api/hooks/services
          signatureKey: X-Pipecd-Signature
          signatureValue: pipecd-playground-signature
