apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: quickstart
  pipedID: c76d43be-8776-4f76-82c4-d8899ebb71b7 ## Project name: pipecd-playground
  pipedKeyData: OXB6NXhpeTAwOHJwdjJ6anVmY3ZvOWI4OWt5dXV4NHVsMDVocjluNjcyNnZ3ZXZiZXQK ## Piped Key: 9pz5xiy008rpv2zjufcvo9b89kyuux4ul05hr9n6726vwevbet
  apiAddress: localhost:8080
  repositories:
    - repoId: pipecd-k8s-manifest-playground
      remote: https://github.com/GotoRen/pipecd-k8s-manifest-playground
      branch: main
  syncInterval: 1m
  platformProviders:
    - name: kubernetes-default
      type: KUBERNETES
      config:
        kubeConfigPath: /Users/ren/.kube/config
  notifications:
    routes:
      ### Webhook
      - name: pipecd-playground-webhook
        events:
          - DEPLOYMENT_SUCCEEDED
          - DEPLOYMENT_FAILED
          - DEPLOYMENT_CANCELLED
        labels:
          env: pipecd-playground
        receiver: pipecd-playground-webhook-receiver
    receivers:
      - name: pipecd-playground-webhook-receiver
        webhook:
          url: http://localhost:8081/api/hooks/services
          signatureKey: X-Pipecd-Signature
          signatureValue: pipecd-playground-signature
