apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    run: nginx
spec:
  selector:
    run: nginx
  ports:
    - name: service-port
      port: 8081
      targetPort: 80
      protocol: TCP
  type: ClusterIP
