apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: apache
  labels:
    env: pipecd-playground
  quickSync:
    prune: true
  input:
    namespace: apache
    kustomizeVersion: 4.5.7
    kustomizeOptions:
      load-restrictor: LoadRestrictionsNone
