apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache
  labels:
    run: apache
spec:
  selector:
    app: apache
  ports:
    - name: service-port
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
